### ISSUE TITLE
qiime2 alpha稀释曲线readsNums异常

### ISSUE THREAD

**Issue by yjiakang** [YuLab-SMU/MicrobiotaProcess#103]
<img width="1896" alt="image" src="https://github.com/YuLab-SMU/MicrobiotaProcess/assets/49177016/4ad036fe-e2e7-4478-a1d1-31ebf73646ab">
您好，感谢开发这个R包，我遇到了一个问题，qiime2 alpha稀释曲线readsNums只有十几。能帮看下原因吗？以下是我的代码：

> mpse <- mp_import_qiime2(otuqza = "merged_all_samples_table_uchime_nc_nm.qza", taxaqza = "taxonomy.qza", mapfilename = "metadata.txt")
> mpse %<>% mp_rrarefy()
> mpse %<>% mp_cal_rarecurve(.abundance = RareAbundance, chunks = 400)
> mpse %>% mp_plot_rarecurve(.rare = RareAbundanceRarecurve, .alpha = Observe, .group = genotype)

**Comment by xiangpin** [comment]
可能是因为你的数据中有一个样本的ASV的总counts数比较少

```
mpse %>% mp_extract_assays(.abundance = Abundance) %>% colSums() %>% sort() %>% rev()
```

https://github.com/YuLab-SMU/MicrobiotaProcess/issues/53#issuecomment-1126662894
