### ISSUE TITLE
parsing the output of qiime2出错

### ISSUE THREAD

**Issue by benzodiazepines** [YuLab-SMU/MicrobiotaProcess#104]
# parsing the output of qiime2
> otuqzafile <- system.file("extdata", "table.qza", package="MicrobiotaProcess")
> taxaqzafile <- system.file("extdata", "taxa.qza", package="MicrobiotaProcess")
> mapfile <- system.file("extdata", "metadata_qza.txt", package="MicrobiotaProcess")
> mpse2 <- mp_import_qiime2(otuqza=otuqzafile, taxaqza=taxaqzafile, mapfilename=mapfile)
> mpse2
ℹ invalid tbl_tree object. Missing column: parent.
ℹ invalid tbl_tree object. Missing column: parent.
ℹ invalid tbl_tree object. Missing column: parent.
ℹ invalid tbl_tree object. Missing column: parent.
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.
ℹ invalid tbl_tree object. Missing column: parent,node.
ℹ invalid tbl_tree object. Missing column: parent,node,label.
! # Invaild edge matrix for <phylo>. A <tbl_df> is returned.
# A MPSE-tibble (MPSE object) abstraction: 12,006 × 32
# OTU=138 | Samples=87 | Assays=Abundance | Taxonomy=Kingdom, Phylum, Class, Order, Family, Genus, Speies
   OTU    Sample   Abundance Sample_Name_s BarcodeSequence LinkerPrimerSequence Subject Sex     Age Pittsburgh
   <chr>  <chr>        <dbl> <chr>         <chr>           <chr>                <chr>   <chr> <int> <chr>     
 1 OTU_1  ERR1331…       901 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 2 OTU_2  ERR1331…       877 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 3 OTU_3  ERR1331…       239 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 4 OTU_4  ERR1331…       201 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 5 OTU_5  ERR1331…       168 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 6 OTU_6  ERR1331…       115 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 7 OTU_7  ERR1331…       107 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 8 OTU_8  ERR1331…        84 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
 9 OTU_9  ERR1331…        67 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
10 OTU_10 ERR1331…        67 LR53          AGTGTCGATTCG    TATGGTAATTGT         Patient Male     63 2         
# ℹ 11,996 more rows
# ℹ 22 more variables: Bell <dbl>, BMI <dbl>, sCD14ugml <dbl>, LBPugml <dbl>, LPSpgml <dbl>, IFABPpgml <dbl>,
#   Physical_functioning <dbl>, Role_physical <dbl>, Role_emotional <dbl>, Energy_fatigue <dbl>,
#   Emotional_well_being <dbl>, Social_functioning <dbl>, Pain <dbl>, General_health <dbl>,
#   Description <lgl>, Kingdom <chr>, Phylum <chr>, Class <chr>, Order <chr>, Family <chr>, Genus <chr>,
#   Speies <chr>
# ℹ Use `print(n = ...)` to see more rows

你好，我分别用了两种方法安装，使用了官方的示例数据，但每次都会报错nvalid tbl_tree object. Missing column: parent.和Invaild edge matrix for <phylo>. A <tbl_df> is returned.，请问是哪儿出了问题呢？谢谢。

**Comment by xiangpin** [comment]
这个不是报错信息，是`MicrobiotaProcess`调用的`tidytree`，`tidytree`内部的提醒信息，可以用`remotes::install_github('YuLab-SMU/MicrobiotaProcess')`下载开发版，或者用`options(check.tbl_tree.verbose = FALSE)`就可以屏蔽这些信息
