### ISSUE TITLE
About ggbartax

### ISSUE THREAD

**Issue by felipe-mansoldo** [YuLab-SMU/MicrobiotaProcess#15]
Hello,

Is there any way to use the factorNames parameter in the ggbartax function? The goal is to have a plot with the x-axis summarized according to factorNames.

thank you

**Comment by xiangpin** [comment]
`ggbartax` has not `factorNames` parameter, but `facetNames` can visualize the abundance of taxonomy of each sample using `facet` with the factor levels.

```
library(MicrobiotaProcess)
library(ggplot2)
data(test_otu_data)
pd <- get_taxadf(test_otu_data, taxlevel=2)
pb <- ggbartax(pd, facetNames="group") + xlab(NULL) + ylab("relative abundance(%)")
pb
```

**Comment by felipe-mansoldo** [comment]
Ok, thank you!
