### ISSUE TITLE
About ggdifftaxbar

### ISSUE THREAD

**Issue by felipe-mansoldo** [YuLab-SMU/MicrobiotaProcess#16]
Hello,

The ggdifftaxbar function exports the figures in .vsg format.
Is there any way to access the method "ggdifftaxbar "," diffAnalysisClass"(https://rdrr.io/bioc/MicrobiotaProcess/src/R/plotdiffAnalysis.R) to change the ggsave device?
I wish I could save it in tiff or png.

Thank you

**Comment by xiangpin** [comment]
The function has not supported saving it to tiff or png. I think you can use `inkscape` to convert `svg` to the format you wanted. Or you can use `rsvg` package to convert it to png.
```
library(rsvg)
rsvg_png("./you.svg", "you.png", width=your_svgwidth * 500, height=your_svgheight * 500)
```

**Comment by felipe-mansoldo** [comment]
Hello,

Good idea.

thank you!
