### ISSUE TITLE
the problem ggtree with MPSE object

### ISSUE THREAD

**Issue by padingdun833** [YuLab-SMU/MicrobiotaProcess#39]
Hi,dear developer!
I have the error as below:
![image](https://user-images.githubusercontent.com/86155600/146481873-4cf26773-2b81-4063-b441-6e5a55dcd177.png)

the code:
setwd("D:\\Personal_profiles\\bioinformatics\\R\\pictures\\circle\\bacteria")
library(ggtree)
library(ggplot2)
library(ggtreeExtra)
otu <- read.csv("otu_taxon.csv",header = T,row.names = 1,check.names = F)
otu <- otu[,-41]
sample <- read.csv("sample_group.csv",header = T,row.names = 1)
taxon <- read.csv("taxon.csv",header = T,row.names = 1)
library(ape)###or  treeio package
tree <- read.tree(file = "phylo_tree.tre")
colnames(otu) <- rownames(sample)[match(colnames(otu),sample$Original_name)]
library(phyloseq)
otu1 <- otu_table(otu,taxa_are_rows=T)
taxon <- as.matrix(taxon)###matrix type
taxon1 <- tax_table(taxon)
sample1 <- sample_data(sample)
physeq <- phyloseq(otu1,taxon1,sample1,tree)
trda_1 <- as.MPSE(physeq)
trda_1%>% mp_cal_abundance(.abundance=Abundance)%>% 
  mp_cal_abundance(.abundance=Abundance, .group=Treatment)%>% 
  mp_diff_analysis(.abundance=RelRareAbundanceBySample, .group=Treatment)%>% 
  mp_extract_tree() -> trda_1
p <- ggtree(trda_1) +
  geom_hilight(
    mapping = aes(
      subset = nodeClass == "Phylum",
      node = node,
      fill = label ))
I wonder where the error is,thanks!

**Comment by xiangpin** [comment]
The `ggtree` doesn't support `MPSE` object, but you had used `mp_extract_tree` to extract the `taxatree` slot, which is `treedata` class supported by `ggtree`. This is corrected. But you should check whether `as.MPSE`  and `mp_diff_analysis` work and whether the taxonomy information contains `Phylum`.

**Comment by padingdun833** [comment]
thanks a lot, the problem is that the `Phylum` is `phylum`.but there is another problem:the relative abundance of OTU in each sample  more than 1.Shouldn't the relative abundance be less than 1？sorry to bother you
![image](https://user-images.githubusercontent.com/86155600/147384351-37d867ae-b5dc-4929-bd08-b60356fcb43e.png)
And the value of legend of relrareabundancebysample I can't understand too.
![image](https://user-images.githubusercontent.com/86155600/147384416-2fbd2e13-d3a9-40c2-9cf2-9b35c6e97d48.png)

**Comment by xiangpin** [comment]
Because the relative abundance (100%) is multiplied by 100.

**Comment by padingdun833** [comment]
thanks a lot!
