### ISSUE TITLE
import data

### ISSUE THREAD

**Issue by YJL900223** [YuLab-SMU/MicrobiotaProcess#4]
> otuqzafile <- system.file("extdata", "table.qza", package="MicrobiotaProcess")
> taxaqzafile <- system.file("extdata", "taxa.qza", package="MicrobiotaProcess")
> mapfile <- system.file("extdata", "metadata_qza.txt", package="MicrobiotaProcess")
> ps_qiime2 <- import_qiime2(otuqza=otuqzafile, taxaqza=taxaqzafile, mapfilename=mapfile)
Error in yaml.load(string, error.label = error.label, ...) : 
  (C:/Users/ADMINI~1.989/AppData/Local/Temp/RtmpiqoKln/c5beb922-6dc5-4f3c-8044-4565641e0f57/VERSION) Scanner error: mapping values are not allowed in this context at line 2, column 8

**Comment by xiangpin** [comment]
I don't konw your R environment, I can run it in R-devel on my window. Please check your R environment, and check the version of yaml.
