### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by quanta123** [YuLab-SMU/MicrobiotaProcess#5]
Due to the differences between the versions of Qiime2 2019 and 2017, the content of the output qza file is also different. Therefore, when reading the qza file output by the 2019 version of Qiime2, an error occurs.

Error in read_biom(file) : Both attempts to read input file:
/var/folders/9j/wn7x1v157wj3tmhlcj4yyjzc0000gn/T//RtmpL1ZXNl/e4af0a5f-8a09-4834-9f86-1f4dbd489edc/VERSION
either as JSON (BIOM-v1) or HDF5 (BIOM-v2).
Check file path, file name, file itself, then try again.
Calls: import_qiime2 -> read.qza -> read.featuretab

**Comment by xiangpin** [comment]
Would you please send me the files? I will try my best to solve the problem.

**Comment by xiangpin** [comment]
My email is xshuangbin@163.com

**Comment by quanta123** [comment]
I have sent the mail, please check it, 3Q.

**Comment by YJL900223** [comment]
I encountered the same problem, did you solve it?

**Comment by xiangpin** [comment]
Yes, the problem is solved.

**Comment by YJL900223** [comment]
Do I need to reinstall the R package

**Comment by xiangpin** [comment]
Yes, You need to reinstall `MicrobiotaProcess`. Thank you!
