### ISSUE TITLE
lapply() to loop over mp_plot_rarecurve()

### ISSUE THREAD

**Issue by tiendu** [YuLab-SMU/MicrobiotaProcess#56]
```
groups <- c("energy.source", "antibiotics", "biochar")
rare_plot <- list()
rare_plot <- lapply(1:length(groups), function(i) {
  mp_plot_rarecurve(
    .data = mpse,
    .rare = RareAbundanceRarecurve,
    .alpha = "Observe",
    .group = groups[i]
    )
})
```

Dear all,

I'm trying to use lapply to create a loop to store the rarecurve plot in a list. But this doesn't work. I got the error messages here.
```
Backtrace:
 1. base::lapply(...)
 2. global FUN(X[[i]], ...)
 4. MicrobiotaProcess::mp_plot_rarecurve(...)
 6. rlang::as_name(.group)
 7. rlang::as_string(x)

Backtrace:
    ▆
 1. └─base::lapply(...)
 2.   └─global FUN(X[[i]], ...)
 3.     ├─MicrobiotaProcess::mp_plot_rarecurve(...)
 4.     └─MicrobiotaProcess::mp_plot_rarecurve(...)
 5.       ├─ggplot2::aes_string(...)
 6.       └─rlang::as_name(.group)
 7.         └─rlang::as_string(x)
 8.           └─rlang:::abort_coercion(x, "a string")
 9.             └─rlang::abort(msg, call = call)
```

**Comment by xiangpin** [comment]
You need to use `!!` to unquote the `.group` argument. You can refer to the [vignettes](https://tidyeval.tidyverse.org/dplyr.html#enquo-and---quote-and-unquote-arguments).

```
groups <- c("energy.source", "antibiotics", "biochar")
rare_plot <- lapply(groups, function(i) {
  mp_plot_rarecurve(
    .data = mpse,
    .rare = RareAbundanceRarecurve,
    .alpha = "Observe",
    .group = !! i
    )
})
```

**Comment by tiendu** [comment]
> You need to use `!!` to unquote the `.group` argument. You can refer to the [vignettes](https://tidyeval.tidyverse.org/dplyr.html#enquo-and---quote-and-unquote-arguments).
> 
> ```
> groups <- c("energy.source", "antibiotics", "biochar")
> rare_plot <- lapply(groups, function(i) {
>   mp_plot_rarecurve(
>     .data = mpse,
>     .rare = RareAbundanceRarecurve,
>     .alpha = "Observe",
>     .group = !! i
>     )
> })
> ```

Thanks Xiangpin,

I didn't know about the rlang unquo.
