### ISSUE TITLE
get_pca(): extract PC1:PC3 % variation explained (values)

### ISSUE THREAD

**Issue by MaryoHg** [YuLab-SMU/MicrobiotaProcess#73]
Dear developers,

Thanks for MicrobiotaProcess package.
I'm unable to get the % variation explained by PC's (PC1, PC2, and PC3).
I got individual and variables PC's to plot, however, I require that piece of information to finish.
Something like:
`# make PCA and get individual and variables data`
`pcares_or <- MicrobiotaProcess::get_pca(obj = data_genus, method = "clr")`
`pcares@pca$???`  to get the % variation explained values for each PC.

Thanks in advance.

**Comment by xiangpin** [comment]
Sorry for replying so late,  the `MicrobiotaProcess` was updated based on `tidy framework`, we now recommend using the newest version. You can install it by `remotes::install_github('YuLab-SMU/MicrobiotaProcess')`. You can also refer to the [vignettes](https://www.bioconductor.org/packages/devel/bioc/vignettes/MicrobiotaProcess/inst/doc/MicrobiotaProcess.html).
Then the variation explained values for each PC can be obtained after `mp_cal_pca`.
```
> library(MicrobiotaProcess)
> data(mouse.time.mpse)
> mouse.time.mpse %>% mp_decostand(.abundance='Abundance', method='clr', pseudocount=1) %>% mp_cal_pca(.abundance=clr) %>% mp_extract_sample()
# A tibble: 19 × 5
   Sample time  `PC1 (35.16%)` `PC2 (10.55%)` `PC3 (8.12%)`
   <chr>  <chr>          <dbl>          <dbl>         <dbl>
 1 F3D0   Early          -6.38         12.4           6.20
 2 F3D1   Early         -12.4           5.45         -1.49
 3 F3D141 Late            8.90          1.02          0.631
 4 F3D142 Late            6.64          0.212         7.48
 5 F3D143 Late            6.97         -1.99          4.06
 6 F3D144 Late            7.32         -2.38          7.08
 7 F3D145 Late            8.08         -0.174         6.28
 8 F3D146 Late            7.48         -1.68         -2.60
 9 F3D147 Late            8.68          1.78         -3.93
10 F3D148 Late           11.9           1.40         -3.73
11 F3D149 Late           11.2           2.98        -10.6
12 F3D150 Late            9.64         -2.57         -3.30
13 F3D2   Early         -14.0          10.2          -2.41
14 F3D3   Early          -4.74         -1.31          2.21
15 F3D5   Early          -7.99          0.344        -3.10
16 F3D6   Early         -11.2          -4.05         -2.91
17 F3D7   Early          -6.39         -4.38          1.11
18 F3D8   Early         -10.9          -7.21         -0.797
19 F3D9   Early         -12.8         -10.0          -0.159
# Then you can use mp_plot_ord to visualize the result
> mouse.time.mpse %>% mp_decostand(.abundance='Abundance', method='clr', pseudocount=1) %>% mp_cal_pca(.abundance=clr) %>% mp_plot_ord(.group=time, .color=time, show.sample=T, show.side=F, ellipse=T)
```
![xx](https://user-images.githubusercontent.com/17870644/198218996-fed7042b-7103-4368-b95f-a6c0153c2f0e.PNG)

**Comment by MaryoHg** [comment]
Dear @xiangpin 

Thanks. I appreciate the commands and example of usage. Clearly I missed to read more in the vignettes. I'll drown into it.

Regards,
