### ISSUE TITLE
Biomarker discovery: Error in if (nrow(tmpkeepfeature) > 0) { : argument is of length zero

### ISSUE THREAD

**Issue by etorres475** [YuLab-SMU/MicrobiotaProcess#87]
Hi!

I am trying to perform the biomarker discovery but keep getting the error: "Error in if (nrow(tmpkeepfeature) > 0) { : argument is of length zero" when running: 

Hca.b.16 %<>%
    mp_diff_analysis(
       .abundance = RelRareAbundanceBySample,
       .group = Plants_grown_in_soil,
       first.test.alpha = 0.01)

I have changed the first.test.alpha to 0.05, `filter.p="pvalue", and used strict = FALSE, but I keep getting the same error. Is there something else I can do? 

<img width="1176" alt="Screenshot 2023-04-10 at 6 21 18 PM" src="https://user-images.githubusercontent.com/128504496/231017389-202791cb-34b4-41f3-b1ed-b8239f2293bd.png">

**Comment by etorres475** [comment]
It is possible that some OTUs have 0 abundance because I am using a subset of the data. Is there a way to ignore those OTUs and continue with the analysis?

**Comment by xiangpin** [comment]
You can use `mp_filter_taxa` to filter the features too low in abundance first.

**Comment by etorres475** [comment]
Thanks a lot for your reply!
I filtered the data, but I keep getting the error! 
<img width="972" alt="Screenshot 2023-04-10 at 10 45 49 PM" src="https://user-images.githubusercontent.com/128504496/231051015-d9c3ef49-80fc-4254-8b5c-e90cbd9df27e.png">
<img width="576" alt="Screenshot 2023-04-10 at 10 46 45 PM" src="https://user-images.githubusercontent.com/128504496/231051024-b6088835-3cba-4a25-8ad0-897324f61b96.png">

**Comment by xiangpin** [comment]
This issue was fixed, you can reinstall `MicrobiotaProcess` via `remotes::install_github('YuLab-SMU/MicrobiotaProcess')`.

**Comment by etorres475** [comment]
Thanks a lot!

<img width="636" alt="Screenshot 2023-04-12 at 2 05 04 AM" src="https://user-images.githubusercontent.com/128504496/231378750-3ff88dc3-2364-4acd-8ff3-abbe9c7b6a90.png">
